import React, { useState } from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import VisGoogleMapComponent from './components/VisGoogleMapComponent'; // Import the new Google Map component
import UserPreferencesModal from './components/UserPreferencesModal';
import './App.css'; // Optional: Include your CSS styles

// // This should be the format of JSON data with the recommended places
// // This will be automatically generated by a function (to be implemented)
// const samplePlaces = [
//   { id: 1, name: 'Place 1', latitude: 36.165, longitude: -86.784 },
//   { id: 2, name: 'Place 2', latitude: 36.167, longitude: -86.781 },
//   { id: 3, name: 'Place 3', latitude: 36.162, longitude: -86.788 },
//   { id: 4, name: 'Place 4', latitude: 36.169, longitude: -86.779 }
// ];

function App() {
  // State to manage modal visibility
  const [showModal, setShowModal] = useState(true); // Modal is shown by default on first load

  // State to store user preferences
   const [userPreferences, setUserPreferences] = useState({});
  
  // State to store places for recommendations
  const [places, setPlaces] = useState([]);

  // Handle modal close
  const handleCloseModal = () => setShowModal(false);

  // Handle form submission from the modal
  const handlePreferencesSubmit = (preferences) => {
    setUserPreferences(preferences);
    console.log('User Preferences:', preferences);

    // Generate or fetch recommendations based on user preferences
    const recommendedPlaces = generateRecommendations(preferences);

    // Set the recommended places
    setPlaces(recommendedPlaces);
  };

  // Placeholder function to generate recommendations based on preferences
  const generateRecommendations = (preferences) => {
    // For now, return a static list of places
    return [
      { id: 1, name: 'Recommended Place 1', latitude: 36.165, longitude: -86.784, imageUrl: 'https://assets.site-static.com/blogphotos/2147/8168-green-spaces-the-top-10-parks-in-nashville-tn-compressed.jpg'},
      { id: 2, name: 'Recommended Place 2', latitude: 36.167, longitude: -86.781, imageUrl: 'https://assets.site-static.com/blogphotos/2147/8168-green-spaces-the-top-10-parks-in-nashville-tn-compressed.jpg'},
      { id: 3, name: 'Recommended Place 3', latitude: 36.162, longitude: -86.788, imageUrl: 'https://assets.site-static.com/blogphotos/2147/8168-green-spaces-the-top-10-parks-in-nashville-tn-compressed.jpg'}
    ];
  };

  return (
    <Router>
      <div className="App">
        <Routes>
          <Route
            path="/"
            element={
              <>
                <h1>Breeze</h1>
                <p>Activity Recommender</p>
                {/* Render the User Preferences Modal */}
                <UserPreferencesModal
                  show={showModal}
                  handleClose={handleCloseModal}
                  onSubmit={handlePreferencesSubmit}
                />

                {/* Render the Vis GL Google Map Component */}
                <VisGoogleMapComponent places={places} />
              </>
            }
          />
        </Routes>
      </div>
    </Router>
  );
}

export default App;
